### ISSUE TITLE
有计划升级到flask 2.0吗

### ISSUE THREAD

**Issue by qdxkrs** [TTWShell/hobbit-core#137]
使用框架生成后，升级整体依赖到flask 2.1.3 报错了，信息如下
Traceback (most recent call last):
  File "E:\GitRepo\flask-demo\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "E:\GitRepo\flask-demo\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "E:\GitRepo\flask-demo\venv\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\GitRepo\flask-demo\venv\lib\site-packages\flask\app.py", line 2080, in wsgi_app
    return response(environ, start_response)
  File "E:\GitRepo\flask-demo\venv\lib\site-packages\werkzeug\wrappers\response.py", line 629, in __call__
    app_iter, status, headers = self.get_wsgi_response(environ)
  File "E:\GitRepo\flask-demo\venv\lib\site-packages\werkzeug\wrappers\response.py", line 615, in get_wsgi_response
    headers = self.get_wsgi_headers(environ)
  File "E:\GitRepo\flask-demo\venv\lib\site-packages\werkzeug\wrappers\response.py", line 506, in get_wsgi_headers
    status = self.status_code
  File "E:\GitRepo\flask-demo\venv\lib\site-packages\werkzeug\sansio\response.py", line 147, in status_code
    return self._status_code
AttributeError: 'Response' object has no attribute '_status_code'

**Comment by TTWShell** [comment]
这个看起来是flask的依赖werkzeug版本不匹配
暂时没时间升级到2.x
